name: Generate Documentation
on:
  workflow_call:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        type: string
        default: 'Release'
      artifact_name:
        description: 'The name of the artifact to upload'
        required: false
        type: string
        default: 'sdkdocs'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install doxygen
        run: sudo apt-get install doxygen

      - name: Bootstrap
        run: |
          cmake -B ${{github.workspace}}/bootstrap -DCMAKE_BUILD_TYPE=${{inputs.build_type}} --install-prefix ${{github.workspace}}
          cmake --build ${{github.workspace}}/bootstrap --config ${{inputs.build_type}} 
          cmake --install ${{github.workspace}}/bootstrap --config ${{inputs.build_type}}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}} --target sdkdocs
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.artifact_name}}
          path: ${{github.workspace}}/build/src/sdk/docs/*