name: Build
on:
  workflow_call:
    inputs:
      build_type:
        description: 'Build type'
        required: false
        type: string
        default: 'Release'
      runner:
        description: 'The machine to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
      artifact_name:
        description: 'The name of the artifact to upload'
        required: false
        type: string
        default: 'linux'

jobs:
  build:
    runs-on: ${{inputs.runner}}
    steps:
      - name: Clean up
        shell: pwsh
        run: |
          Remove-Item -Path ${{github.workspace}} -Recurse -Force -ErrorAction Ignore

      - uses: actions/checkout@v3

      - name: Install doxygen
        if: runner.os == 'Linux'
        run: sudo apt-get install doxygen

      - name: Install doxygen
        if: runner.os == 'Windows'
        run: choco install doxygen.install

      - name: Install doxygen
        if: runner.os == 'macOS'
        run: brew install doxygen

      - name: Bootstrap
        run: |
          cmake -B ${{github.workspace}}/bootstrap -DCMAKE_BUILD_TYPE=${{inputs.build_type}} --install-prefix ${{github.workspace}}
          cmake --build ${{github.workspace}}/bootstrap --config ${{inputs.build_type}} --target install
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Bootstrap Verification
        shell: pwsh
        run: bin/phaka --version

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{inputs.build_type}} --install-prefix ${{github.workspace}}/dist
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{inputs.build_type}} --prefix ${{github.workspace}}/dist
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{inputs.build_type}} --verbose
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run:  cpack --config CPackConfig.cmake -C ${{inputs.build_type}} --verbose
        env:
          BUILD_NUMBER: ${{ github.run_number }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{inputs.artifact_name}}
          path: ${{github.workspace}}/build/artifacts/*

      - name: Clean up
        if: always()
        shell: pwsh
        run: |
          Remove-Item -Path ${{github.workspace}} -Recurse -Force -ErrorAction Ignore