name: Setup
on:
  workflow_call:
    inputs:
      runner:
        description: 'The machine to run on'
        required: false
        type: string
        default: 'ubuntu-latest'
      artifact_name:
        description: 'The name of the artifact to download'
        required: false
        type: string
        default: 'linux'
      package_name:
        description: 'The name of the package to install and run'
        required: true
        type: string
jobs:
  setup:
    runs-on: ${{inputs.runner}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{inputs.artifact_name}}
          path: ${{github.workspace}}

      - name: Print
        run: |
          echo "runner.os: ${{runner.os}}"
          echo "inputs.artifact_name: ${{inputs.artifact_name}}"
          echo "inputs.package_name: ${{inputs.package_name}}"
          echo "inputs.runner: ${{inputs.runner}}"

      - name: Extract ZIP artifact (*nix)
        if: endsWith(inputs.package_name, '.zip') && runner.os != 'windows'
        run: |
          unzip ${{inputs.package_name}} -d ${{github.workspace}}

      - name: Extract ZIP artifact (Windows)
        shell: pwsh
        if: endsWith(inputs.package_name, '.zip') && runner.os == 'windows'
        run: |
          Expand-Archive -Path ${{inputs.package_name}} -DestinationPath ${{github.workspace}}

      - name: Extract TAR.GZ artifact (*nix)
        if: endsWith(inputs.package_name, '.tar.gz') && runner.os != 'windows'
        run: |
          tar -xzf ${{inputs.package_name}} -C ${{github.workspace}}

      - name: Run application
        shell: pwsh
        run: |
          ./bin/phaka --version
          ./bin/phaka arch
          ./bin/phaka system
